# There is an efcore intercceptor that publishes events

### Adds a DomainEvent via efcore interceptor and uses dbContext.SaveChangesAsync to save. 
http://localhost:5141/efcore-with-interceptor

### Adds a DomainEvent in the endpoint and uses dbContext.SaveChangesAsync to save. 
http://localhost:5141/efcore-without-interceptor

### Adds a DomainEvent via efcore interceptor and uses outbox to save. 
http://localhost:5141/outbox-with-interceptor

### Adds a DomainEvent in the endpoint and uses outbox to save. 
http://localhost:5141/outbox-without-interceptor

# None of the 4 above work :(

### just for fun: With this you can check if the DB entry is there
http://localhost:5141/list
